# This is a basic workflow to help you get started with Actions
# これは、アクションを開始するのに役立つ基本的なワークフローです。

name: React Firebase CICD

# Controls when the action will run.
# アクションが実行されるタイミングを制御します。
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  # プッシュまたはプル リクエスト イベントでワークフローをトリガーしますが、マスター ブランチのみを対象とします
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  # [アクション] タブからこのワークフローを手動で実行できます
  workflow_dispatch:c

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
# ワークフローの実行は、順次または並行して実行できる 1 つ以上のジョブで構成されます。
jobs:
  # This workflow contains a single job called "build"
  # このワークフローには、「ビルド」と呼ばれる単一のジョブが含まれています
  build:
    # The type of runner that the job will run on
    # ジョブが実行されるランナーのタイプ
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    # ステップは、ジョブの一部として実行される一連のタスクを表します
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # $GITHUB_WORKSPACE の下にあるリポジトリをチェックアウトして、ジョブがアクセスできるようにします
      - name: Checkout
        uses: actions/checkout@v2

      # Runs a single command using the runners shell
      # runners シェルを使用して単一のコマンドを実行します
      - name: Run a one-line script
        run: echo Start Deploy!

      # Nodeのインストール
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      # runners 依存関係のインストール
      - name: Install Dependencies
        run: |
          npm install
        working-directory: ./

      # ビルド実行
      - name: Build
        run: |
          npm run build
        working-directory: ./

      # デプロイ準備
      - name: Install Firebase Tools
        run: |
          npm install -g firebase-tools
        working-directory: ./

      # デプロイ実行
      # FIREBASE_TOKEN_PRODはGitの環境変数から呼び出される
      - name: Deploy
        env:
          FIREBASE_TOKEN_PROD: ${{ secrets.FIREBASE_TOKEN_PROD }}
        run: |
          firebase deploy --only hosting --token $FIREBASE_TOKEN_PROD
        working-directory: ./
